// import bcrypt from 'bcryptjs';

// const data = {
//   users: [
//     {
//       name: 'Basir',
//       email: 'admin@example.com',
//       password: bcrypt.hashSync('1234', 8),
//       isAdmin: true,
//     },
//     {
//       name: 'John',
//       email: 'user@example.com',
//       password: bcrypt.hashSync('1234', 8),
//       isAdmin: false,
//     },
//   ],
//   products: [
//     {
//       name: 'Mayur',
//       category: 'Pants',
//       image: '/images/p4.jpg',
//       price: 78,
//       countInStock: 15,
//       brand: 'Nike',
//       rating: 4.5,
//       numReviews: 14,
//       description: 'Comfortable and Light Coloured Pant.',
//     },
//     {
//       name: 'Nike Slim Shirt',
//       category: 'Shirts',
//       image: '/images/p1.jpg',
//       price: 120,
//       countInStock: 10,
//       brand: 'Nike',
//       rating: 4.5,
//       numReviews: 10,
//       description: '100% Cotton & Fine Linen Material.',
//     },
//     {
//       name: 'Adidas Fit Shirt',
//       category: 'Shirts',
//       image: '/images/p2.jpg',
//       price: 100,
//       countInStock: 20,
//       brand: 'Adidas',
//       rating: 4.0,
//       numReviews: 10,
//       description: 'Best For Professional Appearances.',
//     },
//     {
//       name: 'Lacoste Free Shirt',
//       category: 'Shirts',
//       image: '/images/p3.jpg',
//       price: 220,
//       countInStock: 0,
//       brand: 'Lacoste',
//       rating: 4.8,
//       numReviews: 17,
//       description: 'A Light Coloured Professional Looking Shirt .',
//     },
//     {
//       name: 'Nike Slim Pant',
//       category: 'Pants',
//       image: '/images/p4.jpg',
//       price: 78,
//       countInStock: 15,
//       brand: 'Nike',
//       rating: 4.5,
//       numReviews: 14,
//       description: 'Comfortable and Light Coloured Pant.',
//     },
//     {
//       name: 'Puma Slim Pant',
//       category: 'Pants',
//       image: '/images/p5.jpg',
//       price: 65,
//       countInStock: 5,
//       brand: 'Puma',
//       rating: 4.5,
//       numReviews: 10,
//       description: 'Best For Professional Appearances.',
//     },
//     {
//       name: 'Puma Royale',
//       category: 'Pants',
//       image: '/images/p6.jpg',
//       price: 65,
//       countInStock: 10,
//       brand: 'Puma',
//       rating: 5,
//       numReviews: 10,
//       description: 'The Ultimate Luxury Clothing with 100% Comfort.',
//     },
//     {
//       name: 'GoPro Camera',
//       category: 'Camera',
//       image: '/images/p7.jpg',
//       price: 600,
//       countInStock: 20,
//       brand: 'GoPro',
//       rating: 5,
//       numReviews: 25,
//       description: 'high quality product',
//     },
//     {
//       name: 'Samsung Tab Pro',
//       category: 'Mobiles and Tablets',
//       image: '/images/p8.jpg',
//       price: 650,
//       countInStock: 25,
//       brand: 'Samsung',
//       rating: 4,
//       numReviews: 25,
//       description: 'A Bigger Size With Enhanced Functionalities.',
//     },
//     {
//       name: 'Apple iPad Pro',
//       category: 'Mobiles and Tablets',
//       image: '/images/p9.jpg',
//       price: 800,
//       countInStock: 5,
//       brand: 'Apple',
//       rating: 5,
//       numReviews: 25,
//       description: 'User-Friendly UI and a Smarter Camera with A13 Bionic Chip',
//     },
//     {
//       name: 'T-Dagger Gaming Mouse',
//       category: 'Gaming',
//       image: '/images/p10.jpg',
//       price: 90,
//       countInStock: 30,
//       brand: 'TDagger',
//       rating: 4,
//       numReviews: 25,
//       description: 'Best For Gaming with a Smoother Movement.',
//     },
//     {
//       name: 'Bose Gaming HeadPhones',
//       category: 'Gaming',
//       image: '/images/p11.jpg',
//       price: 100,
//       countInStock: 20,
//       brand: 'Bose',
//       rating: 5,
//       numReviews: 30,
//       description: 'Noise Cancellation and Enhanced Sound Effects',
//     },
//     {
//       name: 'PlayStation Controller',
//       category: 'Gaming',
//       image: '/images/p12.jpg',
//       price: 35,
//       countInStock: 20,
//       brand: 'PlayStation',
//       rating: 5,
//       numReviews: 25,
//       description: 'Smoother Control Flow with long lasting Durability.',
//     },
//     {
//       name: 'SanDisk MicroSD Card',
//       category: 'HardWare',
//       image: '/images/p14.jpg',
//       price: 40,
//       countInStock: 15,
//       brand: 'SanDisk',
//       rating: 5,
//       numReviews: 25,
//       description: '1 TB Capacity with Amazing Durability.',
//     },
//   ],
// };
// export default data;
import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
     {
      name: 'Udit',
      email: 'abc@gmail.com',
      password: bcrypt.hashSync('123', 8),
      isAdmin: true,
    },
  ],
  products: [
    {
      name: 'IdeaPad Flex 5i(14)',
      category: 'Laptop',
      image: '/images/lenovo_1.jpg',
      price: 55900,
      countInStock: 20,
      brand: 'Lenovo',
      rating: 4.5,
      numReviews: 14,
      description: '11th Generation Intel® Core™ i3-1115G4 Processor,512 GB M.2 2280 SSD',
    },
    {
      name: 'Thinkpad E14',
      category: 'Laptop',
      image: '/images/lenovo_2.jpg',
      price: 47990,
      countInStock: 10,
      brand: 'Lenovo',
      rating: 4.5,
      numReviews: 10,
      description: '11th Generation Intel® Core™ i3-1115G4 Processor,256 GB M.2 2242 SSD',
    },
    {
      name: 'ThinkPad P15v',
      category: 'Laptop',
      image: '/images/lenovo_3.jpg',
      price: 50000,
      countInStock: 20,
      brand: 'Lenovo',
      rating: 4.0,
      numReviews: 10,
      description: '10th Generation Intel® Core™ i5-10300H Processor ,256 GB M.2 2280 SSD',
    },
    {
      name: 'HP Pavilion x360 Touchscreen 2-in-1 ',
      category: 'Laptop',
      image: '/images/hp_1.jpg',
      price: 55000,
      countInStock: 0,
      brand: 'Hp',
      rating: 4.8,
      numReviews: 17,
      description: '10th Gen Core i3-10110U/8GB/512GB SSD/Win 10',
    },
    {
      name: 'Hp Notebook ',
      category: 'Laptop',
      image: '/images/hp_2.jpg',
      price: 43500,
      countInStock: 15,
      brand: 'Hp',
      rating: 4.5,
      numReviews: 14,
      description: 'Core i5 10th Gen - (8 GB/512 GB SSD/Windows 10)',
    },
    {
      name: 'HP 14s-DQ2101TU',
      category: 'Laptop',
      image: '/images/hp_3.jpg',
      price: 52000,
      countInStock: 5,
      brand: 'Hp',
      rating: 4.5,
      numReviews: 10,
      description: '11th Gen Intel Core i3-1115G4/8GB/256GB PCIe-SSD/Intel UHD Graphics/Windows 10/MSO/HD',
    },
    {
      name: 'Inspiron 15 3000',
      category: 'Laptop',
      image: '/images/dell_1.jpg',
      price: 43000,
      countInStock: 10,
      brand: 'Dell',
      rating: 5,
      numReviews: 10,
      description: '11th Generation Intel® Core™ i5-1135G7 Processor ',
    },
    {
      name: 'Dell Inspiron 7306 13"',
      category: 'Laptop',
      image: '/images/dell_2.jpg',
      price: 45700,
      countInStock: 8,
      brand: 'Dell',
      rating: 4.5,
      numReviews: 15,
      description: 'Core i5-1135G7/ 8GB/512GB SSD/ Iris Xe Graphics ',
    },
    {
      name: 'Dell Inspiron 3000 ',
      category: 'Laptop',
      image: '/images/dell_3.jpg',
      price: 70850,
      countInStock: 15,
      brand: 'Dell',
      rating: 5,
      numReviews: 8,
      description: '10th gen i7-1065G7-16GB - 512GB SSD',
    },
    {
      name: 'GoPro Camera',
      category: 'Camera',
      image: '/images/p7.jpg',
      price: 600,
      countInStock: 20,
      brand: 'GoPro',
      rating: 5,
      numReviews: 25,
      description: 'high quality product',
    },
    {
      name: 'Samsung Tab Pro',
      category: 'Mobiles and Tablets',
      image: '/images/p8.jpg',
      price: 650,
      countInStock: 25,
      brand: 'Samsung',
      rating: 4,
      numReviews: 25,
      description: 'A Bigger Size With Enhanced Functionalities.',
    },
    {
      name: 'Apple iPad Pro',
      category: 'Mobiles and Tablets',
      image: '/images/p9.jpg',
      price: 800,
      countInStock: 5,
      brand: 'Apple',
      rating: 5,
      numReviews: 25,
      description: 'User-Friendly UI and a Smarter Camera with A13 Bionic Chip',
    },
    {
      name: 'T-Dagger Gaming Mouse',
      category: 'Gaming',
      image: '/images/p10.jpg',
      price: 90,
      countInStock: 30,
      brand: 'TDagger',
      rating: 4,
      numReviews: 25,
      description: 'Best For Gaming with a Smoother Movement.',
    },
    {
      name: 'Bose Gaming HeadPhones',
      category: 'Gaming',
      image: '/images/p11.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Bose',
      rating: 5,
      numReviews: 30,
      description: 'Noise Cancellation and Enhanced Sound Effects',
    },
    {
      name: 'PlayStation Controller',
      category: 'Gaming',
      image: '/images/p12.jpg',
      price: 35,
      countInStock: 20,
      brand: 'PlayStation',
      rating: 5,
      numReviews: 25,
      description: 'Smoother Control Flow with long lasting Durability.',
    },
    {
      name: 'SanDisk MicroSD Card',
      category: 'HardWare',
      image: '/images/p14.jpg',
      price: 40,
      countInStock: 15,
      brand: 'SanDisk',
      rating: 5,
      numReviews: 25,
      description: '1 TB Capacity with Amazing Durability.',
    },
  ],
};
export default data;